# Introduction to PyTorch

A few links:
- https://github.com/nicknytko/cse-pytorch-workshop
- PyTorch tutorials: https://pytorch.org/tutorials/
- PyTorch manual: https://pytorch.org/docs/stable/index.html
- PyTorch paper: https://openreview.net/forum?id=BJJsrmfCZ
- Calculus on computational graphs: http://colah.github.io/posts/2015-08-Backprop/
- Einstein summation in PyTorch: https://rockt.github.io/2018/04/30/einsum

Pytorch
- 🔥 NumPy-like -- how is it different?
- 🔜 Computes derivatives using a (dynamic) computation graph -- what is this?
- ⏭️ Library of neural nets -- how will we use these?
- ⏭️ Library of optimizers -- why is this important?
- ⏭️ Ability to use GPUs -- where/how?

# Let's get started!

In [1]:
import torch
import numpy as np
import random, datetime
import matplotlib.pyplot as plt
%matplotlib inline

# PyTorch <-> NumPy

PyTorch executes immediately ("eager") versus delayed or lazy execution in TensorFlow.

Tensors are a generalization of a matrix and a vector.  See Einstein notation above!

PyTorch is very picky about datatypes, and defaults to single precision (NumPy defaults to double).

In [2]:
x = torch.tensor([[1.0,2.0,3.0],[4,5,6]])
print(x.dtype)
print(x)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


***
<font color=red>Challenge</font>: force `x` to be `float64`
***

Let's look at a few numpy conversions and numpy-like operations:

In [3]:
x = np.random.rand(3)

y = torch.tensor(x)

z = torch.from_numpy(x)

In [4]:
x[1] = 88
print(x)
print(y)
print(z)

[ 0.6528476  88.          0.27372052]
tensor([0.6528, 0.2930, 0.2737], dtype=torch.float64)
tensor([ 0.6528, 88.0000,  0.2737], dtype=torch.float64)


Notice that `from_numpy()` will create a tensor view of the *same* mameory.  From the docs:
```
Modifications to the tensor will be reflected in the :attr:`ndarray` and vice versa.
```

Operations...

In [5]:
A = torch.tensor([[1.0, 2], [3, 4]])
v = torch.tensor([1.2, 3.4])

A @ v

tensor([ 8.0000, 17.2000])

***
<font color=red>Challenge</font>: write the matvec operation `A @ v` in `.einsum()`
***